### ISSUE TITLE
add other supported sites

### ISSUE THREAD

**Issue by binarygeek119** [Rpsl/metube-browser-extension#1]
metube and youtube-dlp can be used on other site be nice to be able to use on other sites

**Comment by Rpsl** [comment]
actually i don't use another video service and i don't known what need to be supported.
but this task looks very simple - need to be add url match in https://github.com/Rpsl/metube-browser-extension/blob/458ec6f1eb00dc3dbff4f7aabf2d097a7f98c32f/src/background.js#L8

can you help me collect urls for that?

**Comment by binarygeek119** [comment]
i added a pull request for this

**Comment by Rpsl** [comment]
i added "additional sites" feature
