### ISSUE TITLE
Add option to add videos with `auto start = no`

### ISSUE THREAD

**Issue by shawncatz** [Rpsl/metube-browser-extension#15]
Several of the sites that I use this extension and metube to download from will also download other videos from the same page (often videos I already have but have moved to other storage).

The metube app supports adding URLs with `auto start = no`, which will add all of the files from the URL without starting the downloads automatically. This allows me to choose which videos I want vs not.

Could we add an option to the extension to support setting `auto start = no` when we add to metube?

I might be able to make time to put up a PR for this, but I'm not sure when so I thought I would start with an issue.

**Comment by Rpsl** [comment]
Can you provide a test case to better understand the problem?

**Comment by shawncatz** [comment]
Currently, when you go to the `metube` ui and add a URL, you can select `auto start = no`

![Screenshot 2024-01-18 at 3 22 53 AM](https://github.com/Rpsl/metube-browser-extension/assets/1661830/216e7c5a-008c-4af8-9099-3df5e49ef59d)


I would like support for that as an option in the metube extension. I'm not sure how else to explain it.

**Comment by Rpsl** [comment]
If I understand you correctly, you want to collect all links from a web page and send them to metube, but in the current scheme this is not possible.

This extension works with two entities: 
- website url in the browser 
- a link to the video when you right-click.

Or are you talking about `playlist` type links, only without the auto-start?

Can you show an example of a page where the extension is used, and an example of the links that should be passed to metube?

**Comment by shawncatz** [comment]
no, I don't want to get multiple URLs from the page. Some of the sites I use, when adding a single URL to metube (or downloading a single URL with yt-dlp directly) will result in downloading multiple files. I guess this is like a playlist, but the link is not a youtube playlist, it's a link to a page with multiple videos on it.

But all of that doesn't matter.

I want the ability to use the extension to add a url to metube and not automatically start downloading. The request has nothing to do with multiple videos on a url, the only thing that I'm requesting is to be able to add a URL to metube and not automatically start downloading. You could test this with any URL (youtube or otherwise).

If `auto start = yes`, when you add a URL, the video will immediately start downloading
If `auto start = no`, when you add a URL, the video will be added to the queue, but will NOT start downloading

I apologies for any confusion I may have caused

**Comment by Rpsl** [comment]
thanks for explaining. i think it's possible. i will make research in free time soon

**Comment by mutschler** [comment]
@shawncatz you want to do that per video or as global option? might be something to add to my PR if globally is ok for you ;)

**Comment by shawncatz** [comment]
Globally is fine for my use caee. Thanks!

**Comment by mutschler** [comment]
I've added an global Option to disable autostart in the Options here https://github.com/Rpsl/metube-browser-extension/pull/16
