### ISSUE TITLE
Tab switching doesn't work (Chrome macOS)

### ISSUE THREAD

**Issue by stefan786** [Rpsl/metube-browser-extension#18]
With the most current build from the Chrome Webstore (1.7) I cannot get the extension to open and switch to metube (the download is queued but metube isn't opened).

Left-click extension icon:
- Go to MeTube URL: **works**
- Send current tab URL to MeTube (no tab switch): **works**
- Send current tab URL to MeTube and switch to MeTube: **queues the DL but doesn't switch**

Right-click on video preview:
- Send the video URL to MeTube (no tab switch): **works**
- Send the video URL to MeTube and switch to MeTube: **queues the DL but doesn't switch**

May I also suggest adding a masked URL example to readme.md, I had to look in the source to find out what to do ^__^ 

Thanks for this great extension!

**Comment by Rpsl** [comment]
Thx for the report. I will check it in next couple days.

**Comment by Rpsl** [comment]
@stefan786 can you give more info to reproduce the error? Perhaps there are any errors in the extension console?

I have tried reproducing this error on several PCs and everywhere it works as expected. there is a delay of a few seconds before the tab switches, but it is related to the speed of metube response.

**Comment by Rpsl** [comment]
@stefan786 kindly remind

**Comment by stefan786** [comment]
Hi @Rpsl I tested it again today in Chrome and disabled all extensions first -- to my surprise, everything worked as expected! Then I re-enabled all extensions, and it still worked 🙈 I imagine there were a couple of MeTube updates since I've reported my issue, or it resolved itself some other way… My apologies for the false alert.

**Comment by Rpsl** [comment]
@stefan786 time cures all things :)
