### ISSUE TITLE
Right Clicking video and sending to MeTube defaults to webm format

### ISSUE THREAD

**Issue by SpartacusIam** [Rpsl/metube-browser-extension#9]
Is there any way to configure this extension so that when I send videos to metube it uses my metube default of mp4 instead of webm?

**Comment by Rpsl** [comment]
could you clarify, in metube itself you always have mp4 by default and this value is reset when sending via extension?

**Comment by SpartacusIam** [comment]
> could you clarify, in metube itself you always have mp4 by default and this value is reset when sending via extension?

Correct.  Every time I right click on a video and click "Send to Metube" it downloads it in .webm format instead of .mp4.  But if I simply paste the video link in on the metube webui, it downloads the .mp4 correctly.

**Comment by Rpsl** [comment]
it's good feature request, thanks. i think when i did extentsion MeTube didn't have options for choosing video format.

at first look it is not big problem. i will try to implement that shortly.

**Comment by Rpsl** [comment]
changes made in v1.5. new version of the extension has been sent to google store, they usually check quickly.
